import { config } from "dotenv";
import { resolve } from "path";
config({ path: resolve(__dirname, "../.env") });

import { PrismaClient, Role } from "@prisma/client";
import * as bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const CERTS = [
  {
    slug:               "certified-ai-professional",
    acronym:            "CAIP",
    title:              "Certified AI Professional",
    level:              "foundation" as const,
    status:             "active" as const,
    badge_icon:         "🤖",
    price:              495.00,
    sort_order:         1,
    description:        "The essential AI credential for professionals in any industry. Master AI tools, workflows, ethics, and practical applications.",
    long_description:   "The CAIP certification is the professional standard for individuals who work with AI tools, manage AI-driven processes, or advise organizations on AI strategy. Through 42 lessons across 8 comprehensive modules, you'll build practical competency in AI tools, prompt engineering, automation, ethics, governance, and business application. No technical background required — built for professionals, not engineers.",
    duration_weeks:      8,
    total_lessons:       42,
    total_hours:         40,
    passing_score:       70,
    exam_duration_minutes: 90,
    exam_questions_count:  75,
    validity_years:      2,
    max_retakes_included: 2,
    retake_fee:          99.00,
    learning_outcomes: [
      "Apply generative AI tools across business workflows",
      "Write effective prompts for complex professional tasks",
      "Evaluate AI tools and platforms for organizational fit",
      "Design AI governance frameworks for your team or organization",
      "Identify and mitigate AI risks (bias, hallucination, privacy)",
      "Build AI-powered automation for repetitive business processes",
      "Communicate AI strategy and ROI to stakeholders",
      "Stay current with rapidly evolving AI capabilities",
    ],
    target_audience: [
      "Business professionals",
      "Managers and team leads",
      "Educators and trainers",
      "Marketing and communications professionals",
      "Operations managers",
      "HR and talent professionals",
      "Entrepreneurs",
      "Consultants",
    ],
    curriculum_overview: [
      { title: "AI Foundations", description: "How AI works, current landscape, key models and architectures", lessons: 6 },
      { title: "Generative AI Tools & Platforms", description: "ChatGPT, Claude, Gemini, Copilot — practical mastery", lessons: 5 },
      { title: "Prompt Engineering", description: "Advanced prompting techniques for professional applications", lessons: 6 },
      { title: "AI in Business Operations", description: "Automating workflows, productivity, team AI integration", lessons: 5 },
      { title: "AI Ethics & Responsible Use", description: "Bias, hallucination, privacy, governance, regulation", lessons: 6 },
      { title: "Industry Applications", description: "AI in finance, HR, marketing, legal, healthcare, education", lessons: 5 },
      { title: "AI Strategy & ROI", description: "Business cases, stakeholder communication, change management", lessons: 5 },
      { title: "Capstone & Exam Prep", description: "Applied project, practice exam, certification readiness", lessons: 4 },
    ],
    faqs_json: [
      { question: "Do I need a technical background?", answer: "No. CAIP is designed for business professionals, not engineers or data scientists. You'll learn how to use AI tools and think strategically about AI — not how to build models." },
      { question: "How long does it take to complete?", answer: "Most professionals complete CAIP in 6–8 weeks studying 5–7 hours per week. You have unlimited time — no expiration." },
      { question: "Is there a prerequisite for the exam?", answer: "You must complete all 42 lessons and pass all module quizzes before accessing the final exam." },
      { question: "What if I fail the exam?", answer: "Two retakes are included with your enrollment. Additional retakes are $99 each. Detailed score reports help you prepare for retakes." },
      { question: "How is the credential verified?", answer: "Each certificate includes a unique ID and QR code. Employers can verify instantly at paii.ca/verify. Credentials are also integrated with LinkedIn." },
    ],
  },
  {
    slug:               "certified-ai-manager",
    acronym:            "CAIM",
    title:              "Certified AI Manager",
    level:              "advanced" as const,
    status:             "active" as const,
    badge_icon:         "📊",
    price:              1695.00,
    sort_order:         2,
    description:        "Lead AI transformation. Manage AI teams. Build data-driven cultures. For managers driving AI adoption.",
    long_description:   "The CAIM certification prepares managers and team leads to successfully plan, implement, and govern AI initiatives. You'll learn to manage AI-enabled teams, measure ROI, navigate change management challenges, and build the organizational culture needed for AI transformation. CAIP recommended but not required.",
    duration_weeks:      10,
    total_lessons:       55,
    total_hours:         52,
    passing_score:       72,
    exam_duration_minutes: 90,
    exam_questions_count:  75,
    validity_years:      2,
    max_retakes_included: 2,
    retake_fee:          99.00,
    learning_outcomes: [
      "Develop and execute an organizational AI adoption roadmap",
      "Manage cross-functional AI projects from inception to delivery",
      "Build and lead high-performing AI-enabled teams",
      "Measure, track, and communicate AI project ROI",
      "Navigate change management for AI transformation",
      "Establish AI governance frameworks at the team level",
      "Evaluate AI vendors and platforms for organizational needs",
      "Create AI training programs for non-technical staff",
    ],
    target_audience: [
      "Managers",
      "Team leads",
      "Project managers",
      "Product managers",
      "Operations leads",
      "Department heads",
      "AI program leads",
    ],
    curriculum_overview: [
      { title: "AI Management Fundamentals", description: "The manager's role in AI transformation", lessons: 5 },
      { title: "AI Roadmap & Strategy", description: "Planning, prioritization, and business case development", lessons: 6 },
      { title: "Building AI-Ready Teams", description: "Talent, skills assessment, hiring AI roles", lessons: 5 },
      { title: "AI Project Management", description: "Agile AI delivery, sprints, governance", lessons: 7 },
      { title: "Change Management for AI", description: "Adoption psychology, resistance, training programs", lessons: 6 },
      { title: "Measuring AI ROI", description: "KPIs, metrics frameworks, dashboard design", lessons: 5 },
      { title: "AI Vendor Management", description: "RFP process, evaluation criteria, contract terms", lessons: 5 },
      { title: "AI Risk & Compliance", description: "Manager's guide to AI risk, liability, regulation", lessons: 6 },
      { title: "Scaling AI Initiatives", description: "From pilot to enterprise-wide deployment", lessons: 5 },
      { title: "Capstone Project & Exam Prep", description: "Integrated management case study", lessons: 5 },
    ],
    faqs_json: [
      { question: "Is CAIP required before CAIM?", answer: "Recommended but not required. If you have substantial AI experience, you can apply directly for CAIM." },
      { question: "What kind of managers benefit most?", answer: "Any manager who has AI tools or initiatives in their team's scope — from product managers to operations leads to department heads." },
      { question: "Is there a group pricing option?", answer: "Yes. Organizations enrolling 3+ employees receive volume discounts. Contact corporate@paii.ca." },
    ],
  },
  {
    slug:               "certified-ai-educator",
    acronym:            "CAIE",
    title:              "Certified AI Educator",
    level:              "specialist" as const,
    status:             "active" as const,
    badge_icon:         "📚",
    price:              1295.00,
    sort_order:         3,
    description:        "Design and deliver AI-powered learning. For educators, trainers, and L&D professionals shaping how AI is taught.",
    long_description:   "The CAIE certification is built for educators, instructional designers, corporate trainers, and L&D professionals who want to integrate AI into their teaching practice and curriculum design. You'll learn how to use AI tools to create engaging learning experiences, evaluate AI-powered ed-tech platforms, and prepare learners for an AI-driven workplace — responsibly and effectively.",
    duration_weeks:      8,
    total_lessons:       44,
    total_hours:         42,
    passing_score:       70,
    exam_duration_minutes: 90,
    exam_questions_count:  75,
    validity_years:      2,
    max_retakes_included: 2,
    retake_fee:          99.00,
    learning_outcomes: [
      "Design AI-enhanced curriculum for professional and academic contexts",
      "Use generative AI to create learning content, assessments, and resources",
      "Evaluate and implement AI-powered ed-tech platforms",
      "Teach AI literacy concepts to diverse learner groups",
      "Apply ethical frameworks for AI use in education",
      "Personalize learning at scale using AI tools",
      "Measure learning effectiveness of AI-assisted instruction",
      "Prepare learners for AI-driven workplace requirements",
    ],
    target_audience: [
      "K-12 and post-secondary educators",
      "Corporate trainers and facilitators",
      "Instructional designers",
      "L&D managers and specialists",
      "Curriculum developers",
      "Online course creators",
      "Coaching and tutoring professionals",
    ],
    curriculum_overview: [
      { title: "AI in Education Landscape", description: "Current tools, trends, and opportunities in AI-powered learning", lessons: 5 },
      { title: "AI for Content Creation", description: "Generating lessons, slides, assessments, and multimedia with AI", lessons: 6 },
      { title: "Curriculum Design with AI", description: "Learning objectives, scaffolding, and adaptive pathways", lessons: 5 },
      { title: "AI-Powered Ed-Tech Platforms", description: "Evaluating and integrating LMS, tutoring, and assessment tools", lessons: 5 },
      { title: "Teaching AI Literacy", description: "How to teach AI concepts to learners at any level", lessons: 6 },
      { title: "Ethics & Responsible AI in Education", description: "Academic integrity, bias, privacy, and appropriate AI use", lessons: 6 },
      { title: "Personalized & Adaptive Learning", description: "Using AI to differentiate instruction and scale impact", lessons: 5 },
      { title: "Capstone & Exam Prep", description: "Curriculum project, peer review, and certification readiness", lessons: 6 },
    ],
    faqs_json: [
      { question: "Is this for classroom teachers or corporate trainers?", answer: "Both. The CAIE curriculum covers academic, corporate, and online learning contexts. Examples and case studies span K-12, higher education, and professional development." },
      { question: "Do I need CAIP first?", answer: "CAIP is recommended as it establishes your AI foundations. However, experienced educators with solid AI familiarity can apply directly." },
      { question: "What tools does the curriculum cover?", answer: "ChatGPT, Claude, Canva AI, Synthesia, Coursera AI tools, Khanmigo, MagicSchool AI, and major LMS platforms with AI integrations." },
    ],
  },
  {
    slug:               "certified-ai-data-analyst",
    acronym:            "CAIDA",
    title:              "Certified AI Data Analyst",
    level:              "specialist" as const,
    status:             "active" as const,
    badge_icon:         "🔬",
    price:              1495.00,
    sort_order:         4,
    description:        "Advanced AI-powered data analysis and ML interpretation for data professionals.",
    long_description:   "CAIDA bridges the gap between traditional data analytics and modern AI-powered analysis methods. For analysts, data professionals, and BI developers who want to leverage AI models, automate analysis pipelines, and communicate AI-driven insights to business stakeholders.",
    duration_weeks:      10,
    total_lessons:       60,
    total_hours:         58,
    passing_score:       72,
    exam_duration_minutes: 90,
    exam_questions_count:  75,
    validity_years:      2,
    max_retakes_included: 2,
    retake_fee:          99.00,
    learning_outcomes: [
      "Use AI tools to accelerate data analysis workflows",
      "Interpret machine learning model outputs for business decisions",
      "Build AI-assisted data pipelines and automation",
      "Apply statistical AI methods to business problems",
      "Communicate AI-driven insights to non-technical stakeholders",
      "Evaluate data quality and bias in AI systems",
      "Use natural language interfaces for data querying",
      "Design dashboards powered by AI analytics",
    ],
    target_audience: [
      "Data analysts",
      "BI developers",
      "Data scientists (early career)",
      "Reporting analysts",
      "Financial analysts",
      "Marketing analysts",
    ],
    curriculum_overview: [
      { title: "AI for Data Professionals", description: "Landscape, tools, practical orientation", lessons: 5 },
      { title: "AI-Powered Data Wrangling", description: "Automated cleaning, transformation, enrichment", lessons: 6 },
      { title: "Machine Learning for Analysts", description: "Supervised/unsupervised methods, model selection", lessons: 7 },
      { title: "Natural Language Data Interfaces", description: "Text-to-SQL, AI assistants, voice analytics", lessons: 5 },
      { title: "AI Statistical Methods", description: "Forecasting, anomaly detection, clustering", lessons: 7 },
      { title: "AI Dashboard & Visualization", description: "Power BI Copilot, Tableau AI, custom AI viz", lessons: 6 },
      { title: "Data Ethics & Quality", description: "Bias detection, data governance, quality frameworks", lessons: 5 },
      { title: "Communicating AI Insights", description: "Storytelling, executive reporting, uncertainty", lessons: 5 },
      { title: "AI Analysis Automation", description: "Python + AI libraries, workflow automation", lessons: 6 },
      { title: "Capstone Project & Exam Prep", description: "End-to-end AI analytics project", lessons: 8 },
    ],
    faqs_json: [
      { question: "Do I need programming experience?", answer: "Basic familiarity with Excel or SQL is helpful but not required. The CAIDA curriculum focuses on AI tools and interpretation — not writing production code." },
      { question: "What tools does the curriculum cover?", answer: "ChatGPT Advanced Data Analysis, Power BI Copilot, Tableau AI, Julius AI, and Python with AI libraries (pandas-ai, scikit-learn)." },
    ],
  },
  {
    slug:               "executive-ai-leadership",
    acronym:            "EAL",
    title:              "Executive AI Leadership",
    level:              "executive" as const,
    status:             "coming_soon" as const,
    badge_icon:         "🏛️",
    price:              3495.00,
    sort_order:         5,
    description:        "The highest-level PAI credential for C-suite leaders and board members responsible for enterprise AI strategy.",
    long_description:   "The highest-level PAI credential for senior executives, C-suite leaders, and board members responsible for organizational AI strategy, governance, and transformation.",
    duration_weeks:      6,
    total_lessons:       28,
    total_hours:         25,
    passing_score:       70,
    exam_duration_minutes: 75,
    exam_questions_count:  60,
    validity_years:      3,
    max_retakes_included: 2,
    retake_fee:          149.00,
    learning_outcomes: [
      "Enterprise AI governance and board-level oversight",
      "Board-level AI strategy and competitive positioning",
      "AI risk, compliance, and regulatory management",
      "Digital transformation leadership and culture",
      "AI investment prioritization and ROI frameworks",
      "Ethical AI leadership and organizational accountability",
    ],
    target_audience: [
      "CEOs",
      "CTOs",
      "CDOs",
      "CFOs",
      "Board members",
      "VPs",
      "Senior directors",
    ],
    curriculum_overview: [] as any[],
    faqs_json:           [] as any[],
  },
];

async function main() {
  console.log("Seeding database...");

  const adminEmail    = process.env.SUPER_ADMIN_EMAIL    || "admin@paii.ca";
  const adminPassword = process.env.SUPER_ADMIN_PASSWORD || "Admin@123456";

  const admin = await prisma.user.upsert({
    where:  { email: adminEmail },
    update: { password_hash: await bcrypt.hash(adminPassword, 12) },
    create: {
      email:          adminEmail,
      password_hash:  await bcrypt.hash(adminPassword, 12),
      role:           Role.super_admin,
      email_verified: true,
      profile: {
        create: {
          first_name:   "PAI",
          last_name:    "Admin",
          display_name: "PAI Administrator",
        },
      },
    },
  });

  console.log(`Admin user: ${admin.email}`);

  for (const cert of CERTS) {
    const { curriculum_overview, faqs_json, ...rest } = cert;
    const record = await prisma.certification.upsert({
      where:  { slug: cert.slug },
      update: { ...rest, curriculum_overview, faqs_json },
      create: { ...rest, curriculum_overview, faqs_json },
    });
    console.log(`✓ ${record.acronym} — ${record.title}`);
  }

  console.log("\nSeed complete.");
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
